name: Test latest release

on:
  workflow_dispatch:
  
  release:
  
  schedule:
    - cron: '25 0/3 * * *'
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Download latest release
      run: |
        curl -L https://github.com/${{ github.repository }}/releases/latest/download/wedl-linux-amd64 > wedl 
        chmod +x ./wedl
        
    - name: Download wetransfer file
      run: ./wedl https://we.tl/responsibility
      
    - name: Verify downloaded file
      run: | 
        echo "6f8322f2667e7b860cd423b77e1604ca  WeTransfer_Responsible_Business_Report_2020.pdf" | md5sum --check
